### ISSUE TITLE
V3 release

### ISSUE THREAD

**Issue by varnastadeus** [ng-select/ng-select#1250]
- [x] Update to angular 8 #1196
- [x] Use angular cli #1221 
- [x] Move ng-option-highlight to separate package
- [x] #1222 
- [x] feat: add blur method #1238, #1242
- [x] `[excludeGroupsFromDefaultSelection]` - the name is very ambigous and this change was a bit rushed. For now it will be removed until better solution is found 
- [x] other fixes and improvements

**Comment by edocbuhtig** [comment]
@varnastadeus Updated to v3 all is working good and npm warning for angular v8 is now gone, thank you who are involved.

**Comment by varnastadeus** [comment]
don't forget to read about https://github.com/ng-select/ng-select/blob/master/CHANGELOG.md#breaking-changes
